# TODO: Rationalise the boolean conditions to 2 or 3 mutually exclusive parameters
# TODO: Move to config file
fields = [
    {'pipeline': 'PersonID', 'alias': 'PersonID', 'order': 1, 'versioned': 0, 'latestVersion': 0, 'display': 0,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'ConsultationID', 'alias': 'ConsultationID', 'order': 2, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'FirstName', 'alias': 'FirstNameOne', 'order': 3, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'LastName', 'alias': 'LastNameOne', 'order': 4, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'LatestConsultation', 'alias': 'LatestConsultationOne', 'order': 5, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'ExistingCustomer', 'alias': 'ExistingCustomerOne', 'order': 6, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'FirstName', 'alias': 'FirstNameTwo', 'order': 7, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'LastName', 'alias': 'LastNameTwo', 'order': 8, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'LatestConsultation', 'alias': 'LatestConsultationTwo', 'order': 9, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'ExistingCustomer', 'alias': 'ExistingCustomerTwo', 'order': 10, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'TotalCustomers', 'alias': 'TotalCustomers', 'order': 11, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'PracticeName', 'alias': 'PracticeName', 'order': 12, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'PracticeType', 'alias': 'PracticeType', 'order': 13, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'PracticeSite', 'alias': 'PracticeSite', 'order': 14, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'PracticeLicensee', 'alias': 'PracticeLicensee', 'order': 15, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'PracticeState', 'alias': 'PracticeState', 'order': 16, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'AdviserFirstName', 'alias': 'AdviserFirstName', 'order': 17, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'AdviserLastName', 'alias': 'AdviserLastName', 'order': 18, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'ConciergeFirstName', 'alias': 'ConciergeFirstName', 'order': 19, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'ConciergeLastName', 'alias': 'ConciergeLastName', 'order': 20, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'AdviserNotes', 'alias': 'AdviserNotes', 'order': 21, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'InitialFeePackageAmount', 'alias': 'InitialFeePackageAmount', 'order': 22, 'versioned': 0,
     'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'InitialFeePackageDerived', 'alias': 'InitialFeePackageDerived', 'order': 32, 'versioned': 0,
     'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'InitialFeePackageChosen', 'alias': 'InitialFeePackageChosen', 'order': 24, 'versioned': 0,
     'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'DropOut', 'alias': 'DropOut', 'order': 25, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'DropOutDate', 'alias': 'DropOutDate', 'order': 26, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'DropOutReason', 'alias': 'DropOutReason', 'order': 27, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'R1Customer', 'alias': 'R1Customer', 'order': 28, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'ReviewCustomer', 'alias': 'ReviewCustomer', 'order': 29, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'HasPreviousConsultation', 'alias': 'HasPreviousConsultation', 'order': 30, 'versioned': 0,
     'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'ProceedToOnGoingAdvice', 'alias': 'ProceedToOnGoingAdvice', 'order': 31, 'versioned': 0,
     'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'DaysInJourney', 'alias': 'DaysInJourney', 'order': 32, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'LastStepComplete', 'alias': 'LastStepComplete', 'order': 33, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'NextStep', 'alias': 'NextStep', 'order': 34, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'DaysAtStep', 'alias': 'DaysAtStep', 'order': 35, 'versioned': 0, 'latestVersion': 0, 'display': 1,
     'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'NextMeetingType', 'alias': 'NextMeetingType', 'order': 36, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'NextMeetingDate', 'alias': 'NextMeetingDate', 'order': 37, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'FurthestCommitted', 'alias': 'FurthestCommitted', 'order': 38, 'versioned': 0, 'latestVersion': 0,
     'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 1},
    {'pipeline': 'Conversation1MeetingCreated', 'alias': 'Conversation1MeetingFirstCreated', 'order': 40,
     'versioned': 1, 'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation1MeetingCreated', 'alias': 'Conversation1MeetingLastCreated', 'order': 41, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation1MeetingCreated', 'alias': 'Conversation1MeetingCreatedCount', 'order': 42,
     'versioned': 1, 'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation2MeetingCreated', 'alias': 'Conversation2MeetingFirstCreated', 'order': 44,
     'versioned': 1, 'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation2MeetingCreated', 'alias': 'Conversation2MeetingLastCreated', 'order': 45, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation2MeetingCreated', 'alias': 'Conversation2MeetingCreatedCount', 'order': 46,
     'versioned': 1, 'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation3MeetingCreated', 'alias': 'Conversation3MeetingFirstCreated', 'order': 48,
     'versioned': 1, 'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation3MeetingCreated', 'alias': 'Conversation3MeetingLastCreated', 'order': 49, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation3MeetingCreated', 'alias': 'Conversation3MeetingCreatedCount', 'order': 50,
     'versioned': 1, 'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'ReviewMeetingScheduled', 'alias': 'ReviewMeetingScheduled', 'order': 51, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'IntroductoryMeetingScheduled', 'alias': 'IntroductoryMeetingScheduled', 'order': 52, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'AdviceStrategyMeetingScheduled', 'alias': 'AdviceStrategyMeetingScheduled', 'order': 53,
     'versioned': 1, 'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'ProfileCreated', 'alias': 'ProfileCreated', 'order': 54, 'versioned': 1, 'latestVersion': 1,
     'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'RegistrationComplete', 'alias': 'RegistrationComplete', 'order': 55, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation1MeetingScheduled', 'alias': 'Conversation1MeetingScheduled', 'order': 56, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation1MeetingAttended', 'alias': 'Conversation1MeetingAttended', 'order': 57, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'GoalsSummaryDocumentPrepared', 'alias': 'GoalsSummaryDocumentPrepared', 'order': 58, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'InitialClientWorkStarted', 'alias': 'InitialClientWorkStarted', 'order': 59, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'CoreProfile', 'alias': 'CoreProfile', 'order': 60, 'versioned': 1, 'latestVersion': 1, 'display': 1,
     'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'CapitalPreferencesTool', 'alias': 'CapitalPreferencesTool', 'order': 61, 'versioned': 1,
     'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation2MeetingScheduled', 'alias': 'Conversation2MeetingScheduled', 'order': 62, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation2MeetingPrepared', 'alias': 'Conversation2MeetingPrepared', 'order': 63, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation2MeetingAttended', 'alias': 'Conversation2MeetingAttended', 'order': 64, 'versioned': 1,
     'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'StrategyPapersPrepared', 'alias': 'StrategyPapersPrepared', 'order': 65, 'versioned': 1,
     'latestVersion': 0, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'DetailedClientWorkStarted', 'alias': 'DetailedClientWorkStarted', 'order': 66, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'ClientProfileCompleted', 'alias': 'ClientProfileCompleted', 'order': 67, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'ClientProfileReviewed', 'alias': 'ClientProfileReviewed', 'order': 68, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'ClientProfileAccepted', 'alias': 'ClientProfileAccepted', 'order': 69, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'AdviceBuilderCompleted', 'alias': 'AdviceBuilderCompleted', 'order': 70, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'DraftAdviceDocumentFinalised', 'alias': 'DraftAdviceDocumentFinalised', 'order': 71, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation3MeetingScheduled', 'alias': 'Conversation3MeetingScheduled', 'order': 72, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'Conversation3MeetingAttended', 'alias': 'Conversation3MeetingAttended', 'order': 73, 'versioned': 1,
     'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'AuthorityToProceed', 'alias': 'AuthorityToProceed', 'order': 74, 'versioned': 1, 'latestVersion': 1,
     'display': 1, 'eligibleForRunTimeCalculation': 1, 'calculatedAtRunTime': 0},
    {'pipeline': 'StrategyPapersLastModification', 'alias': 'StrategyPapersLastModification', 'order': 75,
     'versioned': 1, 'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'GoalsSummaryDocumentLastModification', 'alias': 'GoalsSummaryDocumentLastModification', 'order': 76,
     'versioned': 1, 'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
    {'pipeline': 'DraftDocumentFinalisedLastModification', 'alias': 'DraftDocumentFinalisedLastModification',
     'order': 77, 'versioned': 1, 'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0,
     'calculatedAtRunTime': 0},
    {'pipeline': 'FinalDocumentsLastModification', 'alias': 'FinalDocumentsLastModification', 'order': 78,
     'versioned': 1, 'latestVersion': 1, 'display': 1, 'eligibleForRunTimeCalculation': 0, 'calculatedAtRunTime': 0},
]